(defpackage :cl-saml-lib/src/core/domain/logout/logout-request
  (:use :cl)
  (:nicknames :logout-request)
  (:import-from :defclass-std)
  (:import-from :cl-saml-lib/src/core/infrastructure/identifiers)
  (:import-from :cl-saml-lib/src/core/infrastructure/time)
  (:import-from :cl-saml-lib/src/core/infrastructure/xml)
  (:import-from :cl-saml-lib/src/core/domain/saml/issuer)
  (:import-from :cl-saml-lib/src/core/domain/saml/name-id)
  (:import-from :cl-saml-lib/src/core/domain/saml/namespaces)
  (:import-from :cl-saml-lib/src/core/infrastructure/idp-config)
  (:export
   #:logout-request
   ;; slots
   #:id
   #:issue-instant
   #:version
   #:destination
   #:not-on-or-after
   #:consent
   #:issuer
   #:name-id
   #:session-index
   ;; constructor (auto-generated by defclass-std)
   #:make-logout-request
   ;; xml
   #:build-logout-request-xml
   #:parse-logout-request-xml
   #:logout-request-to-string
   ;; validation
   #:validate-logout-request
   ;; generation
   #:generate-logout-request-xml
   #:generate-logout-request-from-config))

(in-package :cl-saml-lib/src/core/domain/logout/logout-request)

;;; ──────────────────────────────────────────────
;;; LogoutRequest Domain Class
;;; ──────────────────────────────────────────────

(defclass-std:defclass/std logout-request ()
  ((id :type string)
   (issue-instant :type local-time:timestamp)
   (version :type string)
   (destination :type (or null string))
   (not-on-or-after :type (or null local-time:timestamp))
   (consent :type (or null string))
   (issuer :type (or null issuer:issuer))
   (name-id :type (or null name-id:name-id))
   (session-index :type (or null string)))
  (:documentation "Represents a SAML 2.0 LogoutRequest protocol message."))

;;; ──────────────────────────────────────────────
;;; XML Building
;;; ──────────────────────────────────────────────

(defun build-logout-request-xml (logout-req)
  "Build a samlp:LogoutRequest XML element from a logout-request domain object.
Returns: xml-element"
  (let* ((id-val (id logout-req))
         (issue-instant-val (time:format-saml-time (issue-instant logout-req)))
         (version-val (version logout-req))
         (destination-val (destination logout-req))
         (not-on-or-after-val (not-on-or-after logout-req))
         (consent-val (consent logout-req))
         (issuer-val (issuer logout-req))
         (name-id-val (name-id logout-req))
         (session-index-val (session-index logout-req))
         ;; Build attributes
         (attrs (append
                 `(("ID" ,id-val)
                   ("Version" ,version-val)
                   ("IssueInstant" ,issue-instant-val))
                 (when destination-val
                   `(("Destination" ,destination-val)))
                 (when not-on-or-after-val
                   `(("NotOnOrAfter" ,(time:format-saml-time not-on-or-after-val))))
                 (when consent-val
                   `(("Consent" ,consent-val)))))
         ;; Build children
         (children (append
                    (when issuer-val
                      (list (issuer:build-issuer-xml issuer-val)))
                    (when name-id-val
                      (list (name-id:build-nameid-xml name-id-val)))
                    (when session-index-val
                      (list (xml:make-xml-element
                             (format nil "~A:SessionIndex"
                                     namespaces:+saml-protocol-namespace+)
                             :children (list session-index-val)))))))
    (xml:make-xml-element
     (format nil "~A:LogoutRequest" namespaces:+saml-protocol-namespace+)
     :attributes attrs
     :children children
     :namespace namespaces:+saml-protocol-uri+)))

;;; ──────────────────────────────────────────────
;;; XML Parsing
;;; ──────────────────────────────────────────────

(defun parse-logout-request-xml (source)
  "Parse a LogoutRequest from XML source.
SOURCE: xml-document or xml-element
Returns: logout-request"
  (let ((element (if (typep source 'xml:xml-document)
                     (xml:xml-find-element source
                       (format nil "//~A:LogoutRequest"
                               namespaces:+saml-protocol-namespace+)
                       namespaces:+saml-namespace-declaration+)
                     source)))
    (unless element
      (error "parse-logout-request-xml: No LogoutRequest element found"))
    (let* ((id-val (xml:xml-get-attribute element "ID"))
           (version-val (xml:xml-get-attribute element "Version"))
           (issue-instant-str (xml:xml-get-attribute element "IssueInstant"))
           (destination-val (xml:xml-get-attribute element "Destination"))
           (not-on-or-after-str (xml:xml-get-attribute element "NotOnOrAfter"))
           (consent-val (xml:xml-get-attribute element "Consent"))
           ;; Parse child elements
           (issuer-elem (xml:xml-find-element element
                         (format nil "~A:Issuer" "saml")
                         namespaces:+saml-namespace-declaration+))
           (name-id-elem (xml:xml-find-element element
                          (format nil "~A:NameID" "saml")
                          namespaces:+saml-namespace-declaration+))
           (session-index-elem (xml:xml-find-element element
                                (format nil "~A:SessionIndex"
                                        namespaces:+saml-protocol-namespace+)
                                namespaces:+saml-namespace-declaration+)))
      (make-instance 'logout-request
                     :id id-val
                     :issue-instant (when issue-instant-str
                                      (time:parse-saml-time issue-instant-str))
                     :version (or version-val "2.0")
                     :destination destination-val
                     :not-on-or-after (when not-on-or-after-str
                                        (time:parse-saml-time not-on-or-after-str))
                     :consent consent-val
                     :issuer (when issuer-elem
                               (issuer:parse-issuer-xml issuer-elem))
                     :name-id (when name-id-elem
                                (name-id:parse-nameid-xml name-id-elem))
                     :session-index (when session-index-elem
                                      (xml:xml-element-text-content session-index-elem))))))

;;; ──────────────────────────────────────────────
;;; Serialization
;;; ──────────────────────────────────────────────

(defun logout-request-to-string (logout-req)
  "Serialize a logout-request to an XML string."
  (let* ((element (build-logout-request-xml logout-req))
         (doc (xml:make-xml-element (xml:xml-element-tag element)
                                    :attributes (xml:xml-element-attributes element)
                                    :children (xml:xml-element-children element)
                                    :namespace namespaces:+saml-protocol-uri+)))
    ;; Add namespace declarations
    (dolist (ns namespaces:+saml-namespace-declaration+)
      (destructuring-bind (prefix . uri) ns
        (setf (xml:xml-get-attribute doc (format nil "xmlns:~A" prefix)) uri)))
    (xml:serialize-xml doc :pretty t)))

;;; ──────────────────────────────────────────────
;;; Validation
;;; ──────────────────────────────────────────────

(defun validate-logout-request (logout-req)
  "Validate a LogoutRequest.
Returns: (values valid-p error-message)"
  (cond
    ((null (id logout-req))
     (values nil "LogoutRequest ID is required"))
    ((null (issue-instant logout-req))
     (values nil "LogoutRequest IssueInstant is required"))
    ((not (string= (version logout-req) "2.0"))
     (values nil (format nil "LogoutRequest Version must be 2.0, got ~A"
                         (version logout-req))))
    (t
     (values t nil))))

;;; ──────────────────────────────────────────────
;;; Generation Pipeline
;;; ──────────────────────────────────────────────

(defun generate-logout-request-from-config (idp-config &key name-id session-index)
  "Generate a LogoutRequest domain object from an IdP configuration.
IDP-CONFIG: idp-config instance providing entity-id and SLO URL.
NAME-ID: optional name-id for the user session to terminate.
SESSION-INDEX: optional session index string.
Returns: logout-request instance"
  (let* ((entity-id (idp-config:entity-id idp-config))
         (slo-url (idp-config:slo-url idp-config))
         (request-id (identifiers:generate-saml-id))
         (issue-instant-val (time:current-time)))
    (make-instance 'logout-request
                   :id request-id
                   :issue-instant issue-instant-val
                   :version "2.0"
                   :destination slo-url
                   :issuer (issuer:make-issuer entity-id)
                   :name-id name-id
                   :session-index session-index)))

(defun generate-logout-request-xml (idp-config &key name-id session-index)
  "Generate a LogoutRequest XML string from an IdP configuration.
IDP-CONFIG: idp-config instance.
NAME-ID: optional name-id for the user session to terminate.
SESSION-INDEX: optional session index string.
Returns: XML string"
  (let ((logout-req (generate-logout-request-from-config idp-config
                                                         :name-id name-id
                                                         :session-index session-index)))
    (logout-request-to-string logout-req)))
