(defpackage :cl-saml-lib/src/core/domain/logout/logout-response
  (:use :cl)
  (:nicknames :logout-response)
  (:import-from :defclass-std)
  (:import-from :cl-saml-lib/src/core/infrastructure/identifiers)
  (:import-from :cl-saml-lib/src/core/infrastructure/time)
  (:import-from :cl-saml-lib/src/core/infrastructure/xml)
  (:import-from :cl-saml-lib/src/core/domain/saml/issuer)
  (:import-from :cl-saml-lib/src/core/domain/saml/saml-status)
  (:import-from :cl-saml-lib/src/core/domain/saml/namespaces)
  (:import-from :cl-saml-lib/src/core/infrastructure/idp-config)
  (:export
   #:logout-response
   ;; slots
   #:id
   #:issue-instant
   #:version
   #:destination
   #:in-response-to
   #:issuer
   #:status
   ;; constructor (auto-generated by defclass-std)
   #:make-logout-response
   ;; xml
   #:build-logout-response-xml
   #:parse-logout-response-xml
   #:logout-response-to-string
   ;; validation
   #:validate-logout-response
   ;; generation
   #:generate-logout-response-xml
   #:generate-logout-response-from-config))

(in-package :cl-saml-lib/src/core/domain/logout/logout-response)

;;; ──────────────────────────────────────────────
;;; LogoutResponse Domain Class
;;; ──────────────────────────────────────────────

(defclass-std:defclass/std logout-response ()
  ((id :type string)
   (issue-instant :type time:saml-timestamp)
   (version :type string)
   (destination :type (or null string))
   (in-response-to :type (or null string))
   (issuer :type (or null issuer:issuer))
   (status :type saml-status:saml-status))
  (:documentation "Represents a SAML 2.0 LogoutResponse protocol message."))

;;; ──────────────────────────────────────────────
;;; XML Building
;;; ──────────────────────────────────────────────

(defun build-logout-response-xml (logout-resp)
  "Build a samlp:LogoutResponse XML element from a logout-response domain object.
Returns: xml-element"
  (let* ((id-val (id logout-resp))
         (issue-instant-val (time:format-saml-time (issue-instant logout-resp)))
         (version-val (version logout-resp))
         (destination-val (destination logout-resp))
         (in-response-to-val (in-response-to logout-resp))
         (issuer-val (issuer logout-resp))
         (status-val (status logout-resp))
         ;; Build attributes
         (attrs (append
                 `(("ID" ,id-val)
                   ("Version" ,version-val)
                   ("IssueInstant" ,issue-instant-val))
                 (when destination-val
                   `(("Destination" ,destination-val)))
                 (when in-response-to-val
                   `(("InResponseTo" ,in-response-to-val)))))
         ;; Build children
         (children (append
                    (when issuer-val
                      (list (issuer:build-issuer-xml issuer-val)))
                    (when status-val
                      (list (saml-status:build-status-xml status-val))))))
    (xml:make-xml-element
     (format nil "~A:LogoutResponse" namespaces:+saml-protocol-namespace+)
     :attributes attrs
     :children children
     :namespace namespaces:+saml-protocol-uri+)))

;;; ──────────────────────────────────────────────
;;; XML Parsing
;;; ──────────────────────────────────────────────

(defun parse-logout-response-xml (source)
  "Parse a LogoutResponse from XML source.
SOURCE: xml-document or xml-element
Returns: logout-response"
  (let ((element (if (typep source 'xml:xml-document)
                     (xml:xml-find-element source
                       (format nil "//~A:LogoutResponse"
                               namespaces:+saml-protocol-namespace+)
                       namespaces:+saml-namespace-declaration+)
                     source)))
    (unless element
      (error "parse-logout-response-xml: No LogoutResponse element found"))
    (let* ((id-val (xml:xml-get-attribute element "ID"))
           (version-val (xml:xml-get-attribute element "Version"))
           (issue-instant-str (xml:xml-get-attribute element "IssueInstant"))
           (destination-val (xml:xml-get-attribute element "Destination"))
           (in-response-to-val (xml:xml-get-attribute element "InResponseTo"))
           ;; Parse child elements
           (issuer-elem (xml:xml-find-element element
                         (format nil "~A:Issuer" "saml")
                         namespaces:+saml-namespace-declaration+))
           (status-elem (xml:xml-find-element element
                         (format nil "~A:Status"
                                 namespaces:+saml-protocol-namespace+)
                         namespaces:+saml-namespace-declaration+)))
      (make-logout-response
       :id id-val
       :issue-instant (when issue-instant-str
                        (time:parse-saml-time issue-instant-str))
       :version (or version-val "2.0")
       :destination destination-val
       :in-response-to in-response-to-val
       :issuer (when issuer-elem
                 (issuer:parse-issuer-xml issuer-elem))
       :status (when status-elem
                 (saml-status:parse-status-xml status-elem))))))

;;; ──────────────────────────────────────────────
;;; Serialization
;;; ──────────────────────────────────────────────

(defun logout-response-to-string (logout-resp)
  "Serialize a logout-response to an XML string."
  (let* ((element (build-logout-response-xml logout-resp))
         (doc (xml:make-xml-element (xml:xml-element-tag element)
                                    :attributes (xml:xml-element-attributes element)
                                    :children (xml:xml-element-children element)
                                    :namespace namespaces:+saml-protocol-uri+)))
    ;; Add namespace declarations
    (dolist (ns namespaces:+saml-namespace-declaration+)
      (destructuring-bind (prefix . uri) ns
        (setf (xml:xml-get-attribute doc (format nil "xmlns:~A" prefix)) uri)))
    (xml:serialize-xml doc :pretty t)))

;;; ──────────────────────────────────────────────
;;; Validation
;;; ──────────────────────────────────────────────

(defun validate-logout-response (logout-resp)
  "Validate a LogoutResponse.
Returns: (values valid-p error-message)"
  (cond
    ((null (id logout-resp))
     (values nil "LogoutResponse ID is required"))
    ((null (issue-instant logout-resp))
     (values nil "LogoutResponse IssueInstant is required"))
    ((not (string= (version logout-resp) "2.0"))
     (values nil (format nil "LogoutResponse Version must be 2.0, got ~A"
                         (version logout-resp))))
    ((null (status logout-resp))
     (values nil "LogoutResponse Status is required"))
    (t
     (values t nil))))

;;; ──────────────────────────────────────────────
;;; Generation Pipeline
;;; ──────────────────────────────────────────────

(defun generate-logout-response-from-config (idp-config &key in-response-to status)
  "Generate a LogoutResponse domain object from an IdP configuration.
IDP-CONFIG: idp-config instance providing entity-id and SLO URL.
IN-RESPONSE-TO: the ID of the LogoutRequest being responded to (required).
STATUS: saml-status for the response (default: success).
Returns: logout-response instance"
  (let* ((entity-id (idp-config:entity-id idp-config))
         (slo-url (idp-config:slo-url idp-config))
         (response-id (identifiers:generate-saml-id))
         (issue-instant-val (time:current-time))
         (status-val (or status (saml-status:make-status-success)))
         (logout-resp (make-logout-response
                       :id response-id
                       :issue-instant issue-instant-val
                       :version "2.0"
                       :destination slo-url
                       :in-response-to in-response-to
                       :issuer (issuer:make-issuer entity-id)
                       :status status-val)))
    logout-resp))

(defun generate-logout-response-xml (idp-config &key in-response-to status)
  "Generate a LogoutResponse XML string from an IdP configuration.
IDP-CONFIG: idp-config instance.
IN-RESPONSE-TO: the ID of the LogoutRequest being responded to (required).
STATUS: saml-status for the response (default: success).
Returns: XML string"
  (let ((logout-resp (generate-logout-response-from-config idp-config
                                                           :in-response-to in-response-to
                                                           :status status)))
    (logout-response-to-string logout-resp)))